# Generated by Django 4.2.9 on 2026-02-15 13:35

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='artworks/%Y/%m/%d/', validators=[core.validators.validate_image_size, core.validators.validate_image_format], verbose_name='Rasm')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='S3 URL')),
                ('file_size', models.IntegerField(default=0, verbose_name='Fayl hajmi (bytes)')),
                ('width', models.IntegerField(default=0, verbose_name='Kenglik (px)')),
                ('height', models.IntegerField(default=0, verbose_name='Balandlik (px)')),
                ('format', models.CharField(blank=True, max_length=10, verbose_name='Format')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Baholanmoqda'), ('completed', 'Baholangan'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': "San'at asari",
                'verbose_name_plural': "San'at asarlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi (EN)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Nomi (UZ)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('weight', models.DecimalField(decimal_places=2, help_text="Foizdagi vazn (jami 100% bo'lishi kerak)", max_digits=5, verbose_name='Vazn (%)')),
                ('criteria', models.JSONField(blank=True, default=dict, help_text='Baholash mezonlari (JSON formatda)', verbose_name='Mezonlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
    ]
