# Generated by Django 4.2.9 on 2026-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['user', '-created_at'], name='idx_artwork_user_date'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['status', '-created_at'], name='idx_artwork_status_date'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['status'], name='idx_artwork_status'),
        ),
    ]
