# Generated by Django 4.2.9 on 2026-02-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_artwork_idx_artwork_user_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='criteria_en',
            field=models.JSONField(blank=True, default=dict, help_text='Baholash mezonlari (JSON formatda)', null=True, verbose_name='Mezonlar'),
        ),
        migrations.AddField(
            model_name='category',
            name='criteria_ru',
            field=models.JSONField(blank=True, default=dict, help_text='Baholash mezonlari (JSON formatda)', null=True, verbose_name='Mezonlar'),
        ),
        migrations.AddField(
            model_name='category',
            name='criteria_uz',
            field=models.JSONField(blank=True, default=dict, help_text='Baholash mezonlari (JSON formatda)', null=True, verbose_name='Mezonlar'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi (EN)'),
        ),
    ]
