# Generated by Django 4.2.9 on 2026-02-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_provider', models.CharField(default='claude', max_length=50, verbose_name='LLM Provider')),
                ('llm_model', models.CharField(max_length=100, verbose_name='LLM Model')),
                ('prompt_version', models.CharField(default='1.0', max_length=20, verbose_name='Prompt versiyasi')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Umumiy ball')),
                ('summary', models.TextField(blank=True, verbose_name='Xulosa')),
                ('grade', models.CharField(blank=True, max_length=2, verbose_name='Baho')),
                ('raw_response', models.JSONField(default=dict, verbose_name="LLM to'liq javobi")),
                ('processing_time', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Qayta ishlash vaqti (soniya)')),
                ('api_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='API narxi (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='artworks.artwork', verbose_name="San'at asari")),
            ],
            options={
                'verbose_name': 'Baholash',
                'verbose_name_plural': 'Baholashlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Boshlandi'), ('processing', 'Qayta ishlanmoqda'), ('completed', 'Yakunlandi'), ('failed', 'Xatolik'), ('retried', 'Qayta urinildi')], max_length=20, verbose_name='Harakat')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='evaluations.evaluation', verbose_name='Baholash')),
            ],
            options={
                'verbose_name': 'Baholash tarixi',
                'verbose_name_plural': 'Baholash tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ball (0-100)')),
                ('feedback', models.TextField(blank=True, verbose_name='Tahlil')),
                ('strengths', models.JSONField(blank=True, default=list, verbose_name='Kuchli tomonlar')),
                ('improvements', models.JSONField(blank=True, default=list, verbose_name='Yaxshilanish tavsiyalari')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='artworks.category', verbose_name='Kategoriya')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scores', to='evaluations.evaluation', verbose_name='Baholash')),
            ],
            options={
                'verbose_name': 'Kategoriya balli',
                'verbose_name_plural': 'Kategoriya ballari',
                'ordering': ['category__name'],
                'unique_together': {('evaluation', 'category')},
            },
        ),
    ]
