"""
Official 126-point creative exam rubrics (O'zbekiston Badiiy akademiyasi, 2021, reg. 3314).
"""
from copy import deepcopy

DEFAULT_RUBRIC_SCHEME = 'painting'

FULL_PARTIAL_NONE_RULE = (
    "Har bir mezon: to'liq bajarilsa maksimal ball, qisman bajarilsa maksimal ballning yarmi, "
    "bajarilmasa 0 ball."
)


RUBRIC_SCHEMES = {
    'art_history': {
        'title': "1-bob: San'atshunoslik (tasviriy va amaliy san'at)",
        'max_score': 126,
        'assessment_mode': 'written',
        'time_per_subject_minutes': 80,
        'sections': [
            {
                'key': 'tasviriy_va_amaliy_sanat_tarixi',
                'title': '"Tasviriy va amaliy sanʼat tarixi" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 's1_1_1', 'title': "Tarixiy-siyosiy-ijtimoiy jarayonlar ta'siri", 'max_score': 5},
                    {'key': 's1_1_2', 'title': "Tarixiy sanalarni aniq belgilashi", 'max_score': 5},
                    {'key': 's1_1_3', 'title': "Badiiy uslub xususiyatlari va qiyosiy tahlil", 'max_score': 4},
                    {'key': 's1_1_4', 'title': "Zamonaviy badiiy jarayon haqida ma'lumot", 'max_score': 4},
                    {'key': 's1_1_5', 'title': "Mustaqillik davri milliy san'ati ravnaqi haqida fikr", 'max_score': 4},
                    {'key': 's1_2_1', 'title': "Yevropa rassomlari ijodi va davr tarixini bilishi", 'max_score': 5},
                    {'key': 's1_2_2', 'title': "Rassom tarixiy sanalari va ijodiy bosqichlari", 'max_score': 5},
                    {'key': 's1_2_3', 'title': "Asarlarni bilishi va badiiy tahlil mahorati", 'max_score': 4},
                    {'key': 's1_2_4', 'title': "Kartina sujeti va g'oyasini tahlil qila olishi", 'max_score': 4},
                    {'key': 's1_2_5', 'title': "Asar badiiylik xususiyatlarini anglay olishi", 'max_score': 4},
                    {'key': 's1_3_1', 'title': "Rassom uslublarini farqlay olishi", 'max_score': 5},
                    {'key': 's1_3_2', 'title': "Rassomlar ijodini qiyosiy tavsiflay olishi", 'max_score': 5},
                    {'key': 's1_3_3', 'title': "Badiiy asar kompozitsiyasi haqida tushuncha", 'max_score': 4},
                    {'key': 's1_3_4', 'title': "San'atshunoslik terminlarini qo'llashi", 'max_score': 4},
                    {'key': 's1_3_5', 'title': "Aniq-ravon bayon va mantiqiy uzviy fikrlash", 'max_score': 4},
                ],
            },
            {
                'key': 'ozbekiston_sanati_tarixi',
                'title': "\"O'zbekiston san'ati tarixi\" fani",
                'max_score': 60,
                'criteria': [
                    {'key': 's2_1_1', 'title': "Tarixiy-siyosiy-ijtimoiy jarayonlar ta'siri", 'max_score': 5},
                    {'key': 's2_1_2', 'title': "Davrga oid tarixiy sanalarni belgilashi", 'max_score': 5},
                    {'key': 's2_1_3', 'title': "Uslub xususiyatlari va qiyosiy tasvir", 'max_score': 5},
                    {'key': 's2_1_4', 'title': "Rivojlanish bosqichlari haqida ma'lumot", 'max_score': 5},
                    {'key': 's2_2_1', 'title': "Mustaqillik davri san'ati ravnaqi haqida fikr", 'max_score': 5},
                    {'key': 's2_2_2', 'title': "O'zbekiston muzeylari va hududlarini bilishi", 'max_score': 5},
                    {'key': 's2_2_3', 'title': "Amaliy san'at ustalari ijodi haqida fikr", 'max_score': 5},
                    {'key': 's2_2_4', 'title': "Amaliy san'at turlari haqida fikr", 'max_score': 5},
                    {'key': 's2_3_1', 'title': "Markaziy Osiyo san'ati tarixi haqida fikr", 'max_score': 5},
                    {'key': 's2_3_2', 'title': "Tarixiy-me'moriy obidalar davrlarini farqlashi", 'max_score': 5},
                    {'key': 's2_3_3', 'title': "Tasviriy san'at janrlari haqida ma'lumot", 'max_score': 5},
                    {'key': 's2_3_4', 'title': "O'zbek rassomlari va ijodi haqida fikr", 'max_score': 5},
                ],
            },
        ],
    },
    'painting': {
        'title': '2-bob: Rangtasvir / Professional taʼlim: rangtasvir',
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holatining topilish darajasi', 'max_score': 6},
                    {'key': 'd_4', 'title': "Natura qismlarining o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soyaning ishlanish mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiyaning odam qomatiga mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Tasvirning naturaga o'xshashligi va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Naturaning perspektiv (fazoviy) holati', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Naturaning atrof-muhit bilan bogʻlanganligi', 'max_score': 6},
                    {'key': 'd_10', 'title': "Chizmatasvirning tugallanish darajasi", 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'p_1', 'title': "Formatga nisbatan to'g'ri joylashtirilganligi", 'max_score': 4},
                    {'key': 'p_2', 'title': "Mavzu jihatidan originalligi", 'max_score': 4},
                    {'key': 'p_3', 'title': "Kompozitsion g'oyaviy mazmuni ochib berilishi", 'max_score': 4},
                    {'key': 'p_4', 'title': "G'oya-mazmunning mutaxassislikka xosligi", 'max_score': 4},
                    {'key': 'p_5', 'title': "Badiiy-g'oyaviy ifodada rangdan to'g'ri foydalanish", 'max_score': 4},
                    {'key': 'p_6', 'title': "Qahramon obrazi plastik yechimda topilishi", 'max_score': 4},
                    {'key': 'p_7', 'title': "Tasvirning ta'lim yo'nalishiga mosligi", 'max_score': 4},
                    {'key': 'p_8', 'title': "Kompozitsiya markazining to'g'ri topilishi", 'max_score': 4},
                    {'key': 'p_9', 'title': "Yorug'lik va soyadagi mahorat", 'max_score': 4},
                    {'key': 'p_10', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 4},
                    {'key': 'p_11', 'title': "Yorug'lik-soya mutanosibligi", 'max_score': 4},
                    {'key': 'p_12', 'title': "To'q va och ranglar darajasi", 'max_score': 3},
                    {'key': 'p_13', 'title': 'Issiq va sovuq rang uygʻunligi', 'max_score': 3},
                    {'key': 'p_14', 'title': 'Ranglar orqali atrof-muhit bilan bogʻliqlik', 'max_score': 3},
                    {'key': 'p_15', 'title': "Ranglarning o'zaro mutanosiblik va yaxlitligi", 'max_score': 3},
                    {'key': 'p_16', 'title': "Ranglarning perspektivada o'zgarish holati", 'max_score': 3},
                    {'key': 'p_17', 'title': 'Rakurs va fazoviy holat ishlanishi', 'max_score': 3},
                    {'key': 'p_18', 'title': "Mavzu ma'nosi ochilishi va rang uyg'unligi", 'max_score': 2},
                    {'key': 'p_19', 'title': "Ishlanish mahorati va tugallanish darajasi", 'max_score': 2},
                ],
            },
        ],
    },
    'design_cg_photo': {
        'title': "3-bob: Dizayn (kompyuter grafikasi va badiiy foto)",
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'dcg_1', 'title': "Mavzuni qog'oz tekisligiga to'g'ri joylashtirish", 'max_score': 6.6},
                    {'key': 'dcg_2', 'title': 'Kompozitsion xarakterning ochilishi', 'max_score': 6.6},
                    {'key': 'dcg_3', 'title': "Ranglardan to'g'ri foydalanish", 'max_score': 6.6},
                    {'key': 'dcg_4', 'title': "Kompozitsion g'oyaviy mazmun", 'max_score': 6.6},
                    {'key': 'dcg_5', 'title': "Mavzu jihatidan originallik", 'max_score': 6.6},
                    {'key': 'dcg_6', 'title': "Perspektivani to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dcg_7', 'title': "Tasvirning dizayn mutaxassisligiga mosligi", 'max_score': 6.6},
                    {'key': 'dcg_8', 'title': "Kompozitsiya markazining to'g'ri topilishi", 'max_score': 6.6},
                    {'key': 'dcg_9', 'title': "Mavzu ma'nosi va rang uyg'unligi", 'max_score': 6.6},
                    {'key': 'dcg_10', 'title': 'Ishlanish mahorati va tugallanish', 'max_score': 6.6},
                ],
            },
        ],
    },
    'design_ad_graphics': {
        'title': '3-bob: Dizayn (reklama va amaliy grafika)',
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'dag_1', 'title': "Mavzu kompozitsiyasini tekislikka to'g'ri joylashtirish", 'max_score': 6.6},
                    {'key': 'dag_2', 'title': "Mavzu jihatidan originallik", 'max_score': 6.6},
                    {'key': 'dag_3', 'title': "G'oya-mazmunning mutaxassislikka xosligi", 'max_score': 6.6},
                    {'key': 'dag_4', 'title': "Kompozitsion g'oyaviy mazmun", 'max_score': 6.6},
                    {'key': 'dag_5', 'title': "Ranglardan to'g'ri foydalanish", 'max_score': 6.6},
                    {'key': 'dag_6', 'title': "Perspektivani to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dag_7', 'title': "Tasvirning dizayn mutaxassisligiga mosligi", 'max_score': 6.6},
                    {'key': 'dag_8', 'title': "Kompozitsiya markazining to'g'ri topilishi", 'max_score': 6.6},
                    {'key': 'dag_9', 'title': "Mavzu ma'nosi hamda ranglar uyg'unligi", 'max_score': 6.6},
                    {'key': 'dag_10', 'title': 'Ishlanish mahorati va tugallanish', 'max_score': 6.6},
                ],
            },
        ],
    },
    'design_interior_industrial': {
        'title': '3-bob: Dizayn (interyer / sanoat dizayni)',
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'dii_1', 'title': "Bajarilgan ishning mavzuga mosligi", 'max_score': 6.6},
                    {'key': 'dii_2', 'title': "Mavzu jihatidan originallik", 'max_score': 6.6},
                    {'key': 'dii_3', 'title': "G'oya-mazmunning mutaxassislikka xosligi", 'max_score': 6.6},
                    {'key': 'dii_4', 'title': "Badiiy obraz shakllantirilganligi", 'max_score': 6.6},
                    {'key': 'dii_5', 'title': "Kompozitsion qonun-qoidalarga amal qilinishi", 'max_score': 6.6},
                    {'key': 'dii_6', 'title': "Perspektivani to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dii_7', 'title': "Rang yechimlarini to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dii_8', 'title': "Kompozitsiya markazini to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dii_9', 'title': "Kompozitsiyani tasvirlash mahorati (grafika)", 'max_score': 6.6},
                    {'key': 'dii_10', 'title': 'Ishlanish mahorati va tugallanish', 'max_score': 6.6},
                ],
            },
        ],
    },
    'design_fashion_textile': {
        'title': '3-bob: Dizayn (libos va gazlamalar)',
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'dft_1', 'title': "Bajarilgan ishning mavzuga mosligi", 'max_score': 6.6},
                    {'key': 'dft_2', 'title': "Mavzu jihatidan originallik", 'max_score': 6.6},
                    {'key': 'dft_3', 'title': "G'oya-mazmunning mutaxassislikka xosligi", 'max_score': 6.6},
                    {'key': 'dft_4', 'title': "Badiiy obraz shakllantirilganligi", 'max_score': 6.6},
                    {'key': 'dft_5', 'title': "Perspektivani to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dft_6', 'title': "Kompozitsion qonun-qoidalarga amal qilinishi", 'max_score': 6.6},
                    {'key': 'dft_7', 'title': "Odam gavdasi proporsiyalariga rioya", 'max_score': 6.6},
                    {'key': 'dft_8', 'title': "Rang yechimlarini to'g'ri topish", 'max_score': 6.6},
                    {'key': 'dft_9', 'title': "Kompozitsiyani tasvirlash mahorati (grafika)", 'max_score': 6.6},
                    {'key': 'dft_10', 'title': 'Ishlanish mahorati va tugallanish', 'max_score': 6.6},
                ],
            },
        ],
    },
    'applied_art': {
        'title': "4-bob: Amaliy san'at",
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'aa_1', 'title': "Kompozitsiyaning qog'ozga to'g'ri joylashtirilishi", 'max_score': 4},
                    {'key': 'aa_2', 'title': "Kompozitsiya g'oyasi", 'max_score': 4},
                    {'key': 'aa_3', 'title': "Kompozitsiya mazmuni va mohiyati", 'max_score': 4},
                    {'key': 'aa_4', 'title': "Kompozitsiyaning mutaxassislikka xosligi", 'max_score': 4},
                    {'key': 'aa_5', 'title': "Kompozitsiya qonuniyatlaridan foydalanish", 'max_score': 4},
                    {'key': 'aa_6', 'title': "Asarning kompozitsion yechimi", 'max_score': 4},
                    {'key': 'aa_7', 'title': "Bezaklardan to'g'ri foydalanish", 'max_score': 4},
                    {'key': 'aa_8', 'title': "Asarning kompozitsion ahamiyati", 'max_score': 4},
                    {'key': 'aa_9', 'title': "Badiiy va g'oyaviy ifoda", 'max_score': 4},
                    {'key': 'aa_10', 'title': "Ranglardan to'g'ri foydalanish", 'max_score': 4},
                    {'key': 'aa_11', 'title': "Kompozitsiyaning to'g'ri topilganligi", 'max_score': 4},
                    {'key': 'aa_12', 'title': 'Rangdan foydalanish mahorati', 'max_score': 3},
                    {'key': 'aa_13', 'title': "Kompozitsiya markazini to'g'ri topish", 'max_score': 3},
                    {'key': 'aa_14', 'title': "Kompozitsiyaning murakkablik darajasi", 'max_score': 3},
                    {'key': 'aa_15', 'title': "Ranglar uyg'unligi", 'max_score': 3},
                    {'key': 'aa_16', 'title': "Kompozitsiyaning ishlanish mahorati", 'max_score': 3},
                    {'key': 'aa_17', 'title': "Elementlarning o'zaro mutanosibligi", 'max_score': 3},
                    {'key': 'aa_18', 'title': 'Kompozitsiyani pardozlash', 'max_score': 2},
                    {'key': 'aa_19', 'title': 'Kompozitsiya tugallanish darajasi', 'max_score': 2},
                ],
            },
        ],
    },
    'sculpture': {
        'title': '5-bob: Haykaltaroshlik',
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'sc_1', 'title': "Mavzu jihatidan originallik", 'max_score': 4},
                    {'key': 'sc_2', 'title': "Kompozitsiyaning joylashuvi", 'max_score': 4},
                    {'key': 'sc_3', 'title': "Proporsiyalarning to'g'ri topilishi", 'max_score': 4},
                    {'key': 'sc_4', 'title': 'Rakurs holatining topilishi', 'max_score': 4},
                    {'key': 'sc_5', 'title': 'Xarakterni aniqlash mahorati', 'max_score': 4},
                    {'key': 'sc_6', 'title': 'Plastik yechim', 'max_score': 4},
                    {'key': 'sc_7', 'title': "G'oya-mazmunning mutaxassislikka xosligi", 'max_score': 4},
                    {'key': 'sc_8', 'title': "Asarning kompozitsion g'oyaviy mazmuni", 'max_score': 4},
                    {'key': 'sc_9', 'title': "Badiiy-g'oyaviy ifodali shakl", 'max_score': 4},
                    {'key': 'sc_10', 'title': "Qahramon obrazining plastik yechimi", 'max_score': 4},
                    {'key': 'sc_11', 'title': "Tasvirning haykaltaroshlikka mosligi", 'max_score': 4},
                    {'key': 'sc_12', 'title': "Kompozitsiyaning aylana ko'rinishi", 'max_score': 3},
                    {'key': 'sc_13', 'title': "Kompozitsiyaning perspektiv holati", 'max_score': 3},
                    {'key': 'sc_14', 'title': 'Atrof-muhit bilan uzviy bogʻliqlik', 'max_score': 3},
                    {'key': 'sc_15', 'title': "Kompozitsiyada holatning topilishi", 'max_score': 3},
                    {'key': 'sc_16', 'title': "Mavzu ma'nosi va qomatlar uyg'unligi", 'max_score': 3},
                    {'key': 'sc_17', 'title': "Lepkada shaklning topilishi", 'max_score': 3},
                    {'key': 'sc_18', 'title': 'Material sezish qobiliyati', 'max_score': 2},
                    {'key': 'sc_19', 'title': 'Ishlanish mahorati va tugallanish', 'max_score': 2},
                ],
            },
        ],
    },
    'graphics': {
        'title': '6-bob: Grafika',
        'max_score': 126,
        'assessment_mode': 'practical',
        'time_per_subject_minutes': 160,
        'sections': [
            {
                'key': 'chizmatasvir',
                'title': '"Chizmatasvir" fani',
                'max_score': 60,
                'criteria': [
                    {'key': 'd_1', 'title': 'Naturaning kompozitsion joylashuvi', 'max_score': 6},
                    {'key': 'd_2', 'title': "Proporsiyalarni to'g'ri topilishi", 'max_score': 6},
                    {'key': 'd_3', 'title': 'Rakurs holati', 'max_score': 6},
                    {'key': 'd_4', 'title': "Qismlarning o'zaro nisbiy joylashuvi", 'max_score': 6},
                    {'key': 'd_5', 'title': "Yorug' va soya mahorati", 'max_score': 6},
                    {'key': 'd_6', 'title': "Plastik anatomiya mosligi", 'max_score': 6},
                    {'key': 'd_7', 'title': "Naturaga o'xshashlik va xarakter", 'max_score': 6},
                    {'key': 'd_8', 'title': 'Perspektiv (fazoviy) holat', 'max_score': 6},
                    {'key': 'd_9', 'title': 'Atrof-muhit bilan bogʻliqlik', 'max_score': 6},
                    {'key': 'd_10', 'title': 'Tugallanish darajasi', 'max_score': 6},
                ],
            },
            {
                'key': 'kompozitsiya',
                'title': '"Kompozitsiya" fani',
                'max_score': 66,
                'criteria': [
                    {'key': 'gr_1', 'title': "Formatga nisbatan to'g'ri joylashtirish", 'max_score': 4},
                    {'key': 'gr_2', 'title': "Mavzu jihatidan originallik", 'max_score': 4},
                    {'key': 'gr_3', 'title': "Asarning kompozitsion g'oyaviy mazmuni", 'max_score': 4},
                    {'key': 'gr_4', 'title': "Kompozitsiyaning yaxlitligi", 'max_score': 4},
                    {'key': 'gr_5', 'title': "Ranglardan to'g'ri foydalanish", 'max_score': 4},
                    {'key': 'gr_6', 'title': "Kompozitsion elementlar uyg'unligi", 'max_score': 4},
                    {'key': 'gr_7', 'title': "Qahramonlar obrazi plastik yechimda topilishi", 'max_score': 4},
                    {'key': 'gr_8', 'title': 'Rang tuslarini ajratish mahorati', 'max_score': 4},
                    {'key': 'gr_9', 'title': "Issiq va sovuq ranglardan to'g'ri foydalanish", 'max_score': 4},
                    {'key': 'gr_10', 'title': "Proporsiyalarning to'g'ri topilishi", 'max_score': 4},
                    {'key': 'gr_11', 'title': "Katta-kichik shakllarning to'g'ri joylashuvi", 'max_score': 4},
                    {'key': 'gr_12', 'title': "Yechimning ta'lim yo'nalishiga mosligi", 'max_score': 3},
                    {'key': 'gr_13', 'title': "Kompozitsiya markazini to'g'ri topish", 'max_score': 3},
                    {'key': 'gr_14', 'title': "Kompozitsiyada ketma-ketlik", 'max_score': 3},
                    {'key': 'gr_15', 'title': "Ranglarning perspektivada o'zgarishi", 'max_score': 3},
                    {'key': 'gr_16', 'title': "Mavzu ma'nosi va ranglar uyg'unligi", 'max_score': 3},
                    {'key': 'gr_17', 'title': 'Rakurs va fazoviy holat ishlanishi', 'max_score': 3},
                    {'key': 'gr_18', 'title': "Kompozitsiyaning ishlanish mahorati", 'max_score': 2},
                    {'key': 'gr_19', 'title': "Kompozitsiyaning tugallanish darajasi", 'max_score': 2},
                ],
            },
        ],
    },
}


def get_rubric_scheme(scheme_code):
    """
    Return selected rubric scheme with safe fallback.
    """
    scheme = RUBRIC_SCHEMES.get(scheme_code) or RUBRIC_SCHEMES[DEFAULT_RUBRIC_SCHEME]
    return deepcopy(scheme)


def list_rubric_schemes():
    """
    Lightweight list for API/clients.
    """
    return [
        {
            'code': code,
            'title': payload['title'],
            'max_score': payload['max_score'],
            'assessment_mode': payload['assessment_mode'],
        }
        for code, payload in RUBRIC_SCHEMES.items()
    ]

